### ISSUE TITLE
Force Git to use HTTPS with GitHub

### ISSUE THREAD

**Issue by radioflyer28** [radarku/ardupilot-sitl-docker#10]
**Fix:**  
Add the following to the Dockerfile after installing Git...  
`RUN git config --global url."https://github.com/".insteadOf git://github.com/`

**Reason:**  
GitHub depricated unauthenticated Git protocol on port 9418. Apparently, the Ubuntu 18.04 repo uses a depricated Git config.  
https://github.community/t/cant-show-pull-the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported/242962

**Comment by radarku** [comment]
Sorry for not seeing this until now, @radioflyer28 .  Care to make a PR?

**Comment by radioflyer28** [comment]
> Sorry for not seeing this until now, @radioflyer28 . Care to make a PR?

Sure, I'd be happy to do one

**Comment by radioflyer28** [comment]
@radarku just bumping this into your inbox again, see pull request above
