### ISSUE TITLE
Incorrect Command For Docker Run

### ISSUE THREAD

**Issue by OliverHeilmann** [radarku/ardupilot-sitl-docker#15]
Short one from me! Tried to do a pull request but don't have permissions. In the [README.md options section](https://github.com/radarku/ardupilot-sitl-docker/blob/0200481ac6f428335f0432c373c5840be52c97d6/README.md?plain=1#L57) the command to run a rover docker container is 
```
docker run -it --rm -p 5761:5760 --env VEHICLE=APMRover2 ardupilot
```

Similar deal with [another line](https://github.com/radarku/ardupilot-sitl-docker/blob/0200481ac6f428335f0432c373c5840be52c97d6/README.md?plain=1#L80). This command is not correct as the output with this code is:

```
sim_vehicle.py: error: option --vehicle: invalid choice: 'APMRover2' (choose from 'ArduCopter', 'AntennaTracker', 'APMrover2', 'ArduSub', 'ArduPlane')
```

These two lines should read ```APMrover2``` rather than ```APMRover2```. Alternatively, as all the other types have capital letters, perhaps a parameter change in the docker image is better? Up to you, thought I'd point it out though!

**Comment by radarku** [comment]
Hi @OliverHeilmann - I updated the README to reflect the capitalization; can you confirm that my change addressed your comment completely, please?  If not, please re-open this issue.  Thanks!
